# Generated by Django 4.2.7 on 2023-12-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='_profiles/default.png', upload_to='_profiles'),
        ),
    ]
