# Generated by Django 5.0 on 2023-12-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='images/_songimage/default_artist.png', upload_to='images/_songimage'),
        ),
    ]
