# Generated by Django 5.0 on 2023-12-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/_profiles/default_usr_icon.png', upload_to='images/_profiles'),
        ),
    ]
